# Generated by Django 6.0.1 on 2026-01-10 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='details_json',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='invoices',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.document', verbose_name='Original document'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='seller',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Unit seller'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Unit')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Price')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoices', verbose_name='Thuộc hóa đơn')),
            ],
        ),
    ]
