# Generated by Django 6.0.1 on 2026-01-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No of Receipts'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='seller',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit seller'),
        ),
    ]
