# Generated by Django 6.0.1 on 2026-01-08 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='No of Receipts')),
                ('seller', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit seller')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date purchase')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total money')),
                ('currency', models.CharField(default='VND', max_length=10, verbose_name='Currency')),
                ('raw_text', models.TextField(blank=True, null=True, verbose_name='Raw Text (OCR)')),
                ('details_json', models.TextField(blank=True, null=True, verbose_name='Detail (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date process OCR')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_result', to='core.document', verbose_name='Original document')),
            ],
        ),
    ]
