# Generated by Django 6.0.1 on 2026-01-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
